"""approved column added to users

Revision ID: 5ddaeb1b6b21
Revises: 11cc132a92a8
Create Date: 2025-03-27 03:17:26.651611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddaeb1b6b21'
down_revision = '11cc132a92a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_title'), ['title'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_index('ix_users_username')
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.alter_column('role_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('approved')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_title'))

    # ### end Alembic commands ###
